### ISSUE TITLE
nsert header Fails for temporary files

### ISSUE THREAD

**Issue by nicola-lunghi** [davidquinn/psi-header#25]
```
[2021-10-18 16:05:33.878] [exthost] [error] TypeError: Cannot read property 'getFullYear' of null
	at y2yYear (/home/nicolal/.vscode-server/extensions/psioniq.psi-header-1.15.2/out/src/helper.js:761:51)
	at y2y (/home/nicolal/.vscode-server/extensions/psioniq.psi-header-1.15.2/out/src/helper.js:770:21)
	at Object.getVariables (/home/nicolal/.vscode-server/extensions/psioniq.psi-header-1.15.2/out/src/helper.js:285:43)
	at Object.insertFileHeader (/home/nicolal/.vscode-server/extensions/psioniq.psi-header-1.15.2/out/src/insertFileHeaderCommand.js:52:32)
	at /home/nicolal/.vscode-server/extensions/psioniq.psi-header-1.15.2/out/src/extension.js:44:35
	at l._executeContributedCommand (/home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:94:111652)
	at l.$executeContributedCommand (/home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:94:112090)
	at i._doInvokeHandler (/home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:98:13802)
	at i._invokeHandler (/home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:98:13486)
	at i._receiveRequest (/home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:98:12148)
	at i._receiveOneMessage (/home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:98:10826)
	at /home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:98:8922
	at a.fire (/home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at l.fire (/home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:74:15990)
	at /home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:113:30514
	at a.fire (/home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at l.fire (/home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:74:15990)
	at u._receiveMessage (/home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:74:21260)
	at /home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:74:18138
	at a.fire (/home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at v.acceptChunk (/home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:74:13351)
	at /home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:74:12699
	at a.fire (/home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at /home/nicolal/.vscode-server/bin/c13f1abb110fc756f9b3a6f16670df9cd9d4cf63/out/vs/server/remoteExtensionHostProcess.js:113:19582
	at afterWrite (internal/streams/writable.js:466:5)
	at onwrite (internal/streams/writable.js:446:7)
	at InflateRaw.afterTransform (internal/streams/transform.js:103:3)
	at Zlib.processCallback (zlib.js:586:8) psi-header.insertFileHeader
```

This fails as in `psioniq.psi-header-1.15.2/out/src/helper.js:761:51`
```
function y2yYear(arg, zeroDate = "asIs") {
  ...
    else if (arg.toLowerCase() === 'fc') {
        return getActiveFileCreationDate(zeroDate).getFullYear().toString();
    }
```
but `getActiveFileCreationDate(zeroDate)` doesn't exist (temporary file)

**Comment by davidquinn** [comment]
I have made a change in 1.17 (not yet published) that should resolve this.
